name: Test Auth

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CLAUDE_GITHUB_TOKEN }}
      
      - name: Test
        run: echo "Authentication successful!"